= artworkflow(1)

== NAME
artworkflow - a creatives workflow tracker

== SYNOPSIS
[verse]
*artworkflow* [*--version*|*--help*]
*artworkflow* [_<command>_ [_<arg>_**...**]]

== DESCRIPTION
ArtWorkFlow is a command line creatives workflow tracker.
It allows you to track work, exhibitions, sales, and inventory.

This is a reference, not a tutorial.

When run without arguments or options, the default command is run.

== OPTIONS

*--version*::
Display ArtWorkFlow version information

*--help*::
Display ArtWorkFlow usage information

== ArtWorkFlow commands
ArtWorkFlow supports many commands.
Alphabetically:

*artworkflow-config*(1)::
    Get and set ArtWorkFlow configuration

*artworkflow-diagnostics*(1)::
    Show diagnostic information

*artworkflow-help*(1)::
    Display help

== MORE EXAMPLES


== FILES

=== Non-Unix systems
~/.artworkflow/artworkflow.cfg::
    User configuration file.

~/.artworkflow/data/*.data::
    Data files.

=== Unix systems
${XDG_CONFIG_HOME:-$HOME/.config}/artworkflow/artworkflow.cfg::
    User configuration file if legacy _~/.artworkflow directory doesn't exist.

${XDG_DATA_HOME:-$HOME/.local/share}/artworkflow/data/YYYY-MM.data::
    Time tracking data files if legacy _~/.artworkflow directory doesn't exist.

== pass:[CREDITS & COPYRIGHT]
Copyright (C) 2026 Paul Beckingham
ArtWorkFlow is distributed under the MIT license.
See https://opensource.org/license/mit for more information.

== FURTHER DOCUMENTATION
For more information regarding ArtWorkFlow, see the following:

The official code repository at https://github.com/pbeckingham/artworkflow

You can contact the project by emailing paul@beckingham.net

== REPORTING BUGS
Bugs in ArtWorkFlow may be reported to the issue-tracker at https://github.com/pbeckingham/artworkflow/issues

== SEE ALSO
**artworkflow-tutorial**(7)
**artworkflow-config**(7),
**artworkflow-hints**(7),
